### ISSUE TITLE
Change the font styles

### ISSUE THREAD

**Issue by Ayaon-Norhani** [vergarapog/Garage-Queen-Management-System#26]
![Image](https://github.com/user-attachments/assets/efc92bc9-e0c5-46f0-bc15-080995c247ee)

**Comment by vergarapog** [comment]
Wait lang Ma’am bike muna tayo 🏍️ ![CBD2BF23-F495-4ECB-B8AF-A02E25CB950F](https://github.com/user-attachments/assets/b293f776-7a19-4235-ae08-2a349897d765)
